
package com.company1c.orgregister.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.company1c.orgregister.corporation.CorporationSearchResult;
import com.company1c.orgregister.corporation.CorporationTrustability;
import com.company1c.orgregister.corporation.FnsWebServiceStatus;
import com.company1c.orgregister.corporation.Inspections;
import com.company1c.orgregister.corporation.PersonSearchResult;
import com.company1c.orgregister.corporation.PersonTrustability;
import com.company1c.orgregister.corporation.PersonTrustabilityList;
import com.company1c.orgregister.corporation.РеквизитыИП;
import com.company1c.orgregister.corporation.РеквизитыЮрЛица;
import com.company1c.orgregister.corporation.ФИОТип;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RequisitesWebServiceEndpoint7", targetNamespace = "http://ws.orgregister.company1c.com/")
@XmlSeeAlso({
    com.company1c.orgregister.corporation.ObjectFactory.class,
    com.company1c.orgregister.ws.ObjectFactory.class
})
public interface RequisitesWebServiceEndpoint7 {


    /**
     * 
     * @param regionCode
     * @param address
     * @param name
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.CorporationSearchResult
     */
    @WebMethod
    @WebResult(name = "CorporationSearchResult", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getCorporationRequisitesByNameAndAddress", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByNameAndAddress")
    @ResponseWrapper(localName = "getCorporationRequisitesByNameAndAddressResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByNameAndAddressResponse")
    public CorporationSearchResult getCorporationRequisitesByNameAndAddress(
        @WebParam(name = "name", targetNamespace = "http://ws.orgregister.company1c.com/")
        String name,
        @WebParam(name = "regionCode", targetNamespace = "http://ws.orgregister.company1c.com/")
        String regionCode,
        @WebParam(name = "address", targetNamespace = "http://ws.orgregister.company1c.com/")
        String address,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.РеквизитыЮрЛица
     */
    @WebMethod
    @WebResult(name = "\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b\u042e\u0440\u041b\u0438\u0446\u0430", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getCorporationRequisitesByINN", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByINN")
    @ResponseWrapper(localName = "getCorporationRequisitesByINNResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByINNResponse")
    public РеквизитыЮрЛица getCorporationRequisitesByINN(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.FnsWebServiceStatus
     */
    @WebMethod
    @WebResult(name = "FnsWebServiceStatus", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "updateEntrepreneurByInn", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.UpdateEntrepreneurByInn")
    @ResponseWrapper(localName = "updateEntrepreneurByInnResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.UpdateEntrepreneurByInnResponse")
    public FnsWebServiceStatus updateEntrepreneurByInn(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param regionCode
     * @param address
     * @param directorName
     * @param name
     * @param configurationName
     * @param registeredAfter
     * @return
     *     returns com.company1c.orgregister.corporation.CorporationSearchResult
     */
    @WebMethod
    @WebResult(name = "CorporationSearchResult", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getCorporationRequisitesByNameAndAddressAndDirector", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByNameAndAddressAndDirector")
    @ResponseWrapper(localName = "getCorporationRequisitesByNameAndAddressAndDirectorResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByNameAndAddressAndDirectorResponse")
    public CorporationSearchResult getCorporationRequisitesByNameAndAddressAndDirector(
        @WebParam(name = "name", targetNamespace = "http://ws.orgregister.company1c.com/")
        String name,
        @WebParam(name = "regionCode", targetNamespace = "http://ws.orgregister.company1c.com/")
        String regionCode,
        @WebParam(name = "address", targetNamespace = "http://ws.orgregister.company1c.com/")
        String address,
        @WebParam(name = "directorName", targetNamespace = "http://ws.orgregister.company1c.com/")
        ФИОТип directorName,
        @WebParam(name = "registeredAfter", targetNamespace = "http://ws.orgregister.company1c.com/")
        XMLGregorianCalendar registeredAfter,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.FnsWebServiceStatus
     */
    @WebMethod
    @WebResult(name = "FnsWebServiceStatus", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "updateCorporationByInn", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.UpdateCorporationByInn")
    @ResponseWrapper(localName = "updateCorporationByInnResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.UpdateCorporationByInnResponse")
    public FnsWebServiceStatus updateCorporationByInn(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.Inspections
     */
    @WebMethod
    @WebResult(name = "Inspections", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getInspectionsByInn", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetInspectionsByInn")
    @ResponseWrapper(localName = "getInspectionsByInnResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetInspectionsByInnResponse")
    public Inspections getInspectionsByInn(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.CorporationTrustability
     */
    @WebMethod
    @WebResult(name = "CorporationTrustability", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "checkCorporationTrustability", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.CheckCorporationTrustability")
    @ResponseWrapper(localName = "checkCorporationTrustabilityResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.CheckCorporationTrustabilityResponse")
    public CorporationTrustability checkCorporationTrustability(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param configurationName
     * @param фио
     * @return
     *     returns com.company1c.orgregister.corporation.PersonSearchResult
     */
    @WebMethod
    @WebResult(name = "PersonSearchResult", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getEntrepreneursByName", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetEntrepreneursByName")
    @ResponseWrapper(localName = "getEntrepreneursByNameResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetEntrepreneursByNameResponse")
    public PersonSearchResult getEntrepreneursByName(
        @WebParam(name = "\u0444\u0438\u043e", targetNamespace = "http://ws.orgregister.company1c.com/")
        ФИОТип фио,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.PersonTrustability
     */
    @WebMethod
    @WebResult(name = "PersonTrustability", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "checkPersonTrustabilityByInn", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.CheckPersonTrustabilityByInn")
    @ResponseWrapper(localName = "checkPersonTrustabilityByInnResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.CheckPersonTrustabilityByInnResponse")
    public PersonTrustability checkPersonTrustabilityByInn(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.РеквизитыИП
     */
    @WebMethod
    @WebResult(name = "\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b\u0418\u041f", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getEntrepreneurRequisitesByINN", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetEntrepreneurRequisitesByINN")
    @ResponseWrapper(localName = "getEntrepreneurRequisitesByINNResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetEntrepreneurRequisitesByINNResponse")
    public РеквизитыИП getEntrepreneurRequisitesByINN(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param configurationName
     * @param фио
     * @return
     *     returns com.company1c.orgregister.corporation.PersonTrustabilityList
     */
    @WebMethod
    @WebResult(name = "PersonTrustabilityList", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "checkPersonTrustabilityByName", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.CheckPersonTrustabilityByName")
    @ResponseWrapper(localName = "checkPersonTrustabilityByNameResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.CheckPersonTrustabilityByNameResponse")
    public PersonTrustabilityList checkPersonTrustabilityByName(
        @WebParam(name = "\u0444\u0438\u043e", targetNamespace = "http://ws.orgregister.company1c.com/")
        ФИОТип фио,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

}
