
package com.company1c.orgregister.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.company1c.orgregister.corporation.CorporationSearchResult;
import com.company1c.orgregister.corporation.РеквизитыЮрЛица;
import com.company1c.orgregister.entrepreneur.РеквизитыИП;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RequisitesWebServiceEndpoint2", targetNamespace = "http://ws.orgregister.company1c.com/")
@XmlSeeAlso({
    com.company1c.orgregister.entrepreneur.ObjectFactory.class,
    com.company1c.orgregister.corporation.ObjectFactory.class,
    com.company1c.orgregister.ws.ObjectFactory.class
})
public interface RequisitesWebServiceEndpoint2 {


    /**
     * 
     * @param regionCode
     * @param address
     * @param name
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.CorporationSearchResult
     */
    @WebMethod
    @WebResult(name = "CorporationSearchResult", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getCorporationRequisitesByNameAndAddress", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByNameAndAddress")
    @ResponseWrapper(localName = "getCorporationRequisitesByNameAndAddressResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByNameAndAddressResponse")
    public CorporationSearchResult getCorporationRequisitesByNameAndAddress(
        @WebParam(name = "name", targetNamespace = "http://ws.orgregister.company1c.com/")
        String name,
        @WebParam(name = "regionCode", targetNamespace = "http://ws.orgregister.company1c.com/")
        String regionCode,
        @WebParam(name = "address", targetNamespace = "http://ws.orgregister.company1c.com/")
        String address,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.corporation.РеквизитыЮрЛица
     */
    @WebMethod
    @WebResult(name = "\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b\u042e\u0440\u041b\u0438\u0446\u0430", targetNamespace = "http://company1c.com/orgregister/corporation")
    @RequestWrapper(localName = "getCorporationRequisitesByINN", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByINN")
    @ResponseWrapper(localName = "getCorporationRequisitesByINNResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetCorporationRequisitesByINNResponse")
    public РеквизитыЮрЛица getCorporationRequisitesByINN(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

    /**
     * 
     * @param inn
     * @param configurationName
     * @return
     *     returns com.company1c.orgregister.entrepreneur.РеквизитыИП
     */
    @WebMethod
    @WebResult(name = "\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b\u0418\u041f", targetNamespace = "http://company1c.com/orgregister/entrepreneur")
    @RequestWrapper(localName = "getEntrepreneurRequisitesByINN", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetEntrepreneurRequisitesByINN")
    @ResponseWrapper(localName = "getEntrepreneurRequisitesByINNResponse", targetNamespace = "http://ws.orgregister.company1c.com/", className = "com.company1c.orgregister.ws.GetEntrepreneurRequisitesByINNResponse")
    public РеквизитыИП getEntrepreneurRequisitesByINN(
        @WebParam(name = "INN", targetNamespace = "http://ws.orgregister.company1c.com/")
        String inn,
        @WebParam(name = "configurationName", targetNamespace = "http://ws.orgregister.company1c.com/")
        String configurationName);

}
