
package com.company1c.orgregister.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RequisitesWebServiceEndpointImpl7Service", targetNamespace = "http://ws.orgregister.company1c.com/", wsdlLocation = "https://api.orgregister.1c.ru/orgregister/v7?wsdl")
public class RequisitesWebServiceEndpointImpl7Service
    extends Service
{

    private final static URL REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_WSDL_LOCATION;
    private final static WebServiceException REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_EXCEPTION;
    private final static QName REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_QNAME = new QName("http://ws.orgregister.company1c.com/", "RequisitesWebServiceEndpointImpl7Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.orgregister.1c.ru/orgregister/v7?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_WSDL_LOCATION = url;
        REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_EXCEPTION = e;
    }

    public RequisitesWebServiceEndpointImpl7Service() {
        super(__getWsdlLocation(), REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_QNAME);
    }

    public RequisitesWebServiceEndpointImpl7Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_QNAME, features);
    }

    public RequisitesWebServiceEndpointImpl7Service(URL wsdlLocation) {
        super(wsdlLocation, REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_QNAME);
    }

    public RequisitesWebServiceEndpointImpl7Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_QNAME, features);
    }

    public RequisitesWebServiceEndpointImpl7Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequisitesWebServiceEndpointImpl7Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RequisitesWebServiceEndpoint7
     */
    @WebEndpoint(name = "RequisitesWebServiceEndpointImpl7Port")
    public RequisitesWebServiceEndpoint7 getRequisitesWebServiceEndpointImpl7Port() {
        return super.getPort(new QName("http://ws.orgregister.company1c.com/", "RequisitesWebServiceEndpointImpl7Port"), RequisitesWebServiceEndpoint7.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequisitesWebServiceEndpoint7
     */
    @WebEndpoint(name = "RequisitesWebServiceEndpointImpl7Port")
    public RequisitesWebServiceEndpoint7 getRequisitesWebServiceEndpointImpl7Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.orgregister.company1c.com/", "RequisitesWebServiceEndpointImpl7Port"), RequisitesWebServiceEndpoint7.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_EXCEPTION!= null) {
            throw REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_EXCEPTION;
        }
        return REQUISITESWEBSERVICEENDPOINTIMPL7SERVICE_WSDL_LOCATION;
    }

}
