
package com.company1c.orgregister.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RequisitesWebServiceEndpointImpl2Service", targetNamespace = "http://ws.orgregister.company1c.com/", wsdlLocation = "https://api.orgregister.1c.ru/orgregister/v2?wsdl")
public class RequisitesWebServiceEndpointImpl2Service
    extends Service
{

    private final static URL REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_WSDL_LOCATION;
    private final static WebServiceException REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_EXCEPTION;
    private final static QName REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_QNAME = new QName("http://ws.orgregister.company1c.com/", "RequisitesWebServiceEndpointImpl2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.orgregister.1c.ru/orgregister/v2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_WSDL_LOCATION = url;
        REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_EXCEPTION = e;
    }

    public RequisitesWebServiceEndpointImpl2Service() {
        super(__getWsdlLocation(), REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_QNAME);
    }

    public RequisitesWebServiceEndpointImpl2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_QNAME, features);
    }

    public RequisitesWebServiceEndpointImpl2Service(URL wsdlLocation) {
        super(wsdlLocation, REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_QNAME);
    }

    public RequisitesWebServiceEndpointImpl2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_QNAME, features);
    }

    public RequisitesWebServiceEndpointImpl2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequisitesWebServiceEndpointImpl2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RequisitesWebServiceEndpoint2
     */
    @WebEndpoint(name = "RequisitesWebServiceEndpointImpl2Port")
    public RequisitesWebServiceEndpoint2 getRequisitesWebServiceEndpointImpl2Port() {
        return super.getPort(new QName("http://ws.orgregister.company1c.com/", "RequisitesWebServiceEndpointImpl2Port"), RequisitesWebServiceEndpoint2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequisitesWebServiceEndpoint2
     */
    @WebEndpoint(name = "RequisitesWebServiceEndpointImpl2Port")
    public RequisitesWebServiceEndpoint2 getRequisitesWebServiceEndpointImpl2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.orgregister.company1c.com/", "RequisitesWebServiceEndpointImpl2Port"), RequisitesWebServiceEndpoint2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_EXCEPTION!= null) {
            throw REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_EXCEPTION;
        }
        return REQUISITESWEBSERVICEENDPOINTIMPL2SERVICE_WSDL_LOCATION;
    }

}
